version: "3.8"
services:
  client:
#    开启的服务名称
    stdin_open: true
#    标准输入
    build:
      context: .
#      编译本地环境
      dockerfile: Dockerfile

    ports:
      - '8080:8080'
    volumes:
      - '/todoMVC/node_modules'
      - './:/todoMVC'
#      本地todoMVC所有文件都绑定到。/文件中去
    depends_on:
      - database
    #        依赖关系
  database:
     build:
      context: .
      #      编译本地环境
      dockerfile: Dockerfile
     ports:
       - '4000:4000'
     volumes:
       - './data:/todoMVC/data/db.json'
     restart: always
